function isValidEmailAddress(emailAddress){var pattern=new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);return pattern.test(emailAddress);}
$(function(){$('.mobile_menu').click(function(e){e.preventDefault();$('html').toggleClass('no_scroll');$(this).toggleClass('active');$('.nav_menu').toggleClass('active');});$('select').niceSelect();$(".checkbox").click(function(){$(this).find('.block').toggleClass('active');$(this).find('input:checkbox').attr('checked',$(this).find('.block').hasClass('active')).change()});$('.dataimages').each(function(){$(this).css({'background':'#12100c url('+$(this).data('src')+')','background-size':$(this).data('size'),'background-position':'center','background-repeat':'no-repeat'});});var count_anim=0;setInterval(function(){if(!count_anim){$('.img_text, .text_play, #btn_start').removeClass('zoomInDown');$('.img_text, .text_play, .input_wrap .x2').addClass('pulse');$('#btn_start, .download').addClass('headShake');count_anim=1;}
else{$('.img_text, .text_play, .input_wrap .x2').removeClass('pulse');$('#btn_start, .download').removeClass('headShake');}},1900);setInterval(function(){$('.img_text, .text_play, .input_wrap .x2').addClass('pulse');$('#btn_start, .download').addClass('headShake');},2000);let payments_gateway_type='unitpay'
$('#donate_gateway_types').on('click','> .donate-gateways__option',function(evt){const $parent=$(this).parent()
let type='unitpay'
if($(this).hasClass('donate-gateways__option_qiwi'))type='qiwip2p'
if($(this).hasClass('donate-gateways__option_unitpay'))type='unitpay'
$parent.children('div').removeClass('donate-gateways__option_active')
$(this).addClass('donate-gateways__option_active')
$parent.children('input').val(type)
payments_gateway_type=type});$('#donate_window #ofert').change(function(){$('#donate_window #pay_btn').prop('disabled',!this.checked)});$("#donate_window #donate").submit(function(event){event.preventDefault();if($('#donate_window #ofert').is(":checked")){var el=$(this);$.ajax({type:el.attr('method'),url:el.attr('action'),data:new FormData(this),contentType:false,cache:false,processData:false,success:function(result){console.log(result);json=jQuery.parseJSON(result);if(json.status=="warning")el.find('.alert').html(json.message);else{$('#donate_window').hide();$('#confirm_window').show();$('#serverDonate').html(json.server_name);$('#nickName').html(json.name);$('#valueSum').html(json.sum);if(payments_gateway_type==='unitpay'){$('#email_confirm').parent().show()
$('#confirm_window .info').html($('#confirm_window .info').html()+'</br>Адрес, на который будет отправлен чек, введите ниже:')}
else{$('#email_confirm').parent().hide()
$('#confirm_window .info').html($('#confirm_window .info').attr('x-default-html'))}
if($('.x2').hasClass('disabled')){if(json.sum>500&&json.sum<1000)$('#pcCount').html(Math.round((json.sum)+json.sum*0.15));else if(json.sum>1000&&json.sum<1500)$('#pcCount').html(Math.round((json.sum)+json.sum*0.2));else if(json.sum>1500)$('#pcCount').html(Math.round((json.sum)+json.sum*0.3));else $('#pcCount').html(json.sum);}
else $('#pcCount').html(json.sum*2);$('#pay_go').attr('href',json.url);}}});}
else return alert('Вы не подтвердили соглашение');});$("#pay_go").click(function(event){event.preventDefault();if(payments_gateway_type==='unitpay'){if($('#email_confirm').val()){if(isValidEmailAddress($('#email_confirm').val())){window.location=$(this).attr('href')+"&customerEmail="+$('#email_confirm').val();}else alert('Почта введена неверно');}else alert('Введите свою почту');}
else{window.location=$(this).attr('href');}});$('#cancel_pay').click(function(){$('#donate_window').removeClass('slideInLeft');$('#confirm_window').hide();setTimeout(()=>{$('#donate_window').show();},199);setTimeout(()=>{$('#donate_window').addClass('slideInLeft');},200);});$("#packages").submit(function(event){event.preventDefault();if($('#ofert_modal').is(":checked")){if($('#email_confirm_modal').val()){if(!isValidEmailAddress($('#email_confirm_modal').val()))return alert('Почта введена неверно');}
var el=$(this);$.ajax({type:$(this).attr('method'),url:$(this).attr('action'),data:new FormData(this),contentType:false,cache:false,processData:false,success:function(result){json=jQuery.parseJSON(result);if(json.status=="warning"){el.find('.alert').html(json.message);}
else{window.location=json.url;}}});}
else return alert('Вы не подтвердили соглашение');});});var app=new Vue({el:'#app_block',data:{},methods:{openMobile:function(event){},openBuyPackages:function(id){if(id==0)return alert('Недоступно для покупки');var datas=event.target;$.ajax({type:'GET',url:'/unitpay/loadpackages',data:'id='+id,contentType:false,cache:false,processData:false,success:function(result){json=jQuery.parseJSON(result);if(json.error){alert('Ошибка! Перезагрузите страницу');return 1;}
$('#modalBuy').modal('show');$('#modalBuy #id_modal').val(id);$('#modalBuy .modal-body').html('<h4>Игровые пакеты в разработке</h4><br><p>Воспользуйтесь пополнением счёта</p>')}});},}});